#!/usr/bin/env sh
status=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | sed '12q;d' | cut -d' ' -f 20)
if [ "$status" = "charging" ]; then
	time=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | sed '20q;d' | cut -d' ' -f 15-16)
else
	time=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | sed '20q;d' | cut -d' ' -f 14-16)
fi
echo "(""$time"")"
