(map! :leader "," nil)
(map! :leader "." nil)
(map! :leader
      (:prefix ("," . "open bookmarked folder")
:desc "~/courses/tda342_advanced_functional_programming" "afp" (lambda! (neotree-dir "~/courses/tda342_advanced_functional_programming"))
:desc "/home/carlb/Downloads" "D" (lambda! (neotree-dir "/home/carlb/Downloads"))
:desc "~/courses" "cc" (lambda! (neotree-dir "~/courses"))
:desc "~/.config" "cf" (lambda! (neotree-dir "~/.config"))
:desc "~/courses/datx02_kandidatarbete/Kandidatarbete-NES-Emulator" "ck" (lambda! (neotree-dir "~/courses/datx02_kandidatarbete/Kandidatarbete-NES-Emulator"))
:desc "~/dev/c" "dc" (lambda! (neotree-dir "~/dev/c"))
:desc "~/dotfiles" "dd" (lambda! (neotree-dir "~/dotfiles"))
:desc "~/dev/elm" "de" (lambda! (neotree-dir "~/dev/elm"))
:desc "~/dev/python" "dp" (lambda! (neotree-dir "~/dev/python"))
:desc "~/courses/eda322_digital_design/EDA322-Labs" "di" (lambda! (neotree-dir "~/courses/eda322_digital_design/EDA322-Labs"))
:desc "~/courses/dat326" "dsl" (lambda! (neotree-dir "~/courses/dat326"))
:desc "~/" "h" (lambda! (neotree-dir "~/"))
:desc "~/music" "m" (lambda! (neotree-dir "~/music"))
:desc "/mnt" "M" (lambda! (neotree-dir "/mnt"))
:desc "~/org" "o" (lambda! (neotree-dir "~/org"))
:desc "~/pictures" "pp" (lambda! (neotree-dir "~/pictures"))
:desc "~/.scripts" "sc" (lambda! (neotree-dir "~/.scripts"))
:desc "~/videos" "vv" (lambda! (neotree-dir "~/videos"))
)
(:prefix ("." . "open bookmarked file")
:desc "~/.bmdirs" "bd" (lambda! (find-file "~/.bmdirs"))
:desc "~/.bmfiles" "bf" (lambda! (find-file "~/.bmfiles"))
:desc "~/.bashrc" "cfb" (lambda! (find-file "~/.bashrc"))
:desc "~/.config/compton/config" "cfc" (lambda! (find-file "~/.config/compton/config"))
:desc "~/git/dwm/config.h" "cfd" (lambda! (find-file "~/git/dwm/config.h"))
:desc "~/.config/i3/config" "cfi" (lambda! (find-file "~/.config/i3/config"))
:desc "~/.config/kitty/kitty.conf" "cfk" (lambda! (find-file "~/.config/kitty/kitty.conf"))
:desc "~/.config/lf/lfrc" "cfl" (lambda! (find-file "~/.config/lf/lfrc"))
:desc "~/.config/polybar/config.ini" "cfp" (lambda! (find-file "~/.config/polybar/config.ini"))
:desc "~/.config/ranger/rc.conf" "cfr" (lambda! (find-file "~/.config/ranger/rc.conf"))
:desc "~/.spacemacs" "cfs" (lambda! (find-file "~/.spacemacs"))
:desc "~/.vimrc" "cfv" (lambda! (find-file "~/.vimrc"))
:desc "~/.zshrc" "cfz" (lambda! (find-file "~/.zshrc"))
:desc "~/Documents/LaTeX/cv.tex" "cv" (lambda! (find-file "~/Documents/LaTeX/cv.tex"))
))